// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lic.extracter.domain;

import com.lic.extracter.domain.ExtraAlchemer;
import com.lic.extracter.service.ExtraAlchemerService;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ExtraAlchemerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ExtraAlchemerDataOnDemand: @Component;
    
    private Random ExtraAlchemerDataOnDemand.rnd = new SecureRandom();
    
    private List<ExtraAlchemer> ExtraAlchemerDataOnDemand.data;
    
    @Autowired
    ExtraAlchemerService ExtraAlchemerDataOnDemand.extraAlchemerService;
    
    public ExtraAlchemer ExtraAlchemerDataOnDemand.getNewTransientExtraAlchemer(int index) {
        ExtraAlchemer obj = new ExtraAlchemer();
        setCategory(obj, index);
        setInquiryDate(obj, index);
        setKeywords(obj, index);
        setNamedEntities(obj, index);
        setRelations(obj, index);
        setUrl(obj, index);
        setUrlContent(obj, index);
        return obj;
    }
    
    public void ExtraAlchemerDataOnDemand.setCategory(ExtraAlchemer obj, int index) {
        String category = "category_" + index;
        obj.setCategory(category);
    }
    
    public void ExtraAlchemerDataOnDemand.setInquiryDate(ExtraAlchemer obj, int index) {
        String inquiryDate = "inquiryDate_" + index;
        obj.setInquiryDate(inquiryDate);
    }
    
    public void ExtraAlchemerDataOnDemand.setKeywords(ExtraAlchemer obj, int index) {
        String keywords = "keywords_" + index;
        obj.setKeywords(keywords);
    }
    
    public void ExtraAlchemerDataOnDemand.setNamedEntities(ExtraAlchemer obj, int index) {
        String namedEntities = "namedEntities_" + index;
        obj.setNamedEntities(namedEntities);
    }
    
    public void ExtraAlchemerDataOnDemand.setRelations(ExtraAlchemer obj, int index) {
        String relations = "relations_" + index;
        obj.setRelations(relations);
    }
    
    public void ExtraAlchemerDataOnDemand.setUrl(ExtraAlchemer obj, int index) {
        String url = "url_" + index;
        obj.setUrl(url);
    }
    
    public void ExtraAlchemerDataOnDemand.setUrlContent(ExtraAlchemer obj, int index) {
        String urlContent = "urlContent_" + index;
        obj.setUrlContent(urlContent);
    }
    
    public ExtraAlchemer ExtraAlchemerDataOnDemand.getSpecificExtraAlchemer(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ExtraAlchemer obj = data.get(index);
        java.math.BigInteger id = obj.getId();
        return extraAlchemerService.findExtraAlchemer(id);
    }
    
    public ExtraAlchemer ExtraAlchemerDataOnDemand.getRandomExtraAlchemer() {
        init();
        ExtraAlchemer obj = data.get(rnd.nextInt(data.size()));
        java.math.BigInteger id = obj.getId();
        return extraAlchemerService.findExtraAlchemer(id);
    }
    
    public boolean ExtraAlchemerDataOnDemand.modifyExtraAlchemer(ExtraAlchemer obj) {
        return false;
    }
    
    public void ExtraAlchemerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = extraAlchemerService.findExtraAlchemerEntries(from, to);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ExtraAlchemer' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.lic.extracter.domain.ExtraAlchemer>();
        for (int i = 0; i < 10; i++) {
            ExtraAlchemer obj = getNewTransientExtraAlchemer(i);
            try {
                extraAlchemerService.saveExtraAlchemer(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
