// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lic.extracter.alchemy;

import java.lang.String;

privileged aspect AlchemyCredential_Roo_ToString {
    
    public String AlchemyCredential.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("AlchemyApiKey: ").append(getAlchemyApiKey());
        return sb.toString();
    }
    
}
